# execution-environment.yml
# Ansible Builder definition for NetBox-enabled execution environment

---
version: 3

images:
  base_image:
    name: quay.io/ansible/awx-ee:latest

dependencies:
  galaxy: requirements.yml
  system: bindep.txt
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner

additional_build_steps:
  append_final:
    - RUN pip3 install --no-cache-dir pynetbox