# execution-environment.yml
# Ansible Builder definition for NetBox-enabled execution environment

---
version: 3

images:
  base_image:
    name: quay.io/ansible/awx-ee:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner

additional_build_files:
  - src: requirements.txt
    dest: requirements.txt