AWX:
  # enable use of awx-deploy template
  enabled: enable
  name: awx
  spec:
    admin_user: admin
    ingress_type: ingress
    hostname: awx.local
    service_type: ClusterIP

  # configurations for external postgres instance
  postgres:
    enabled: false
    host: Unset
    port: 5678
    dbName: Unset
    username: admin
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: Unset
    sslmode: prefer
    type: unmanaged

rbac:
  create: true

operator-controller: {}

operator-controller-containers: {}

