### THIS IS NOT PRODUCTION GRADE, DO NOT USE IN PRODUCTION ###

apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: ${VAULT_TOKEN_BASE64}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://${LOCAL_IP_ADDRESS}:8200"
      path: "secret"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"